QLTour/WebTour/Controllers/KhachHangsController.cs
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using BusAndModel.Model;
using BusAndModel.BUS;

namespace WebTour.Controllers
{
    public class KhachHangsController : Controller
    {
        KhachhangBus bus = new KhachhangBus();

        // GET: KhachHangs
        public ActionResult Index()
        {
            List<KhachHang> list = bus.getList();
            return View(list);
        }

        // GET: KhachHangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = bus.FindbyId(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // GET: KhachHangs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KhachHangs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,HoTen,CMND,DiaChi,SDT,GioiTinh")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                bus.CreateKhachHang(khachHang);
                return RedirectToAction("Index");
            }

            return View(khachHang);
        }

        // GET: KhachHangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = bus.FindbyId(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HoTen,CMND,DiaChi,SDT,GioiTinh")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                bus.UpdateKhachHang(khachHang);
                return RedirectToAction("Index");
            }
            return View(khachHang);
        }
        public ActionResult Delete(int? id)
        {
            bus.DeleteKhachHang(id);
            return RedirectToAction("Index");
        }

    }
}

QLTour/WebTour/Views/KhachHangs/Create.cshtml
@using BusAndModel.Model
@model KhachHang

@{
    ViewBag.Title = "Create";
}

<h2>Đăng Ký Khách Hàng</h2>


@using (Html.BeginForm("Create", "KhachHangs", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="box-header with-border">
        <h3 class="box-title">Thêm thông tin hành khách</h3>
        <div class="box-tools pull-right">
            <button type="submit" class="btn btn-box-tool">
                <i class="fa fa-check" style="font-size:16px"></i>
            </button>
            <span class="btn btn-box-tool" onclick="location.href='/KhachHangs/Index'">
                <i class="fa fa-times" style="font-size:16px"></i>
            </span>
        </div>
    </div>
    <div class="box-body">
        <div class="row">
            @Html.AntiForgeryToken()
            <!-------------------------------------COL12------------------------------------>
            <div class="col-md-12">
                <div class="form-group minHeight80">
                    <label>Họ và Tên</label>
                    @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Nhập họ..." } })
                    @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
                </div>

                <div class="form-group minHeight80">
                    <label>Số CMND</label>

                    @Html.EditorFor(model => model.CMND, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Nhập số CMND..." } })
                    @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })

                </div>

                <div class="form-group minHeight80">
                    <label>Địa chỉ liên hệ</label>
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Nhập địa chỉ..." } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>

                <div class="form-group minHeight80">
                    <label>Số điện thoại</label>
                    @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Nhập Số điện thoại..." } })
                    @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                </div>
                <div class="form-group minHeight80">
                    <label>Giới Tính</label>
                    @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Nhập Giới tính..." } })
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>

               
            </div>
        </div>
    </div>
}

QLTour/WebTour/Views/KhachHangs/Delete.cshtml
@model BusAndModel.Model.KhachHang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KhachHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CMND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QLTour/WebTour/Views/KhachHangs/Details.cshtml
@model BusAndModel.Model.KhachHang

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>KhachHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CMND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QLTour/WebTour/Views/KhachHangs/Edit.cshtml
@model BusAndModel.Model.KhachHang

@{
    ViewBag.Title = "Cập nhật thông tin khách hàng";
}



@using (Html.BeginForm("Edit", "KhachHangs", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="box-header with-border">
        <h3 class="box-title">Thêm thông tin hành khách</h3>
        <div class="box-tools pull-right">
            <button type="submit" class="btn btn-box-tool">
                <i class="fa fa-check" style="font-size:16px"></i>
            </button>
            <span class="btn btn-box-tool" onclick="location.href='/KhachHangs/Index'">
                <i class="fa fa-times" style="font-size:16px"></i>
            </span>
        </div>
    </div>
    <div class="box-body">
        <div class="row">
            @Html.AntiForgeryToken()
            <!-------------------------------------COL12------------------------------------>
            <div class="col-md-12">
                <div class="form-group minHeight80">
                    <label>Họ và Tên</label>
                    @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Nhập họ..." } })
                    @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
                </div>

                <div class="form-group minHeight80">
                    <label>Số CMND</label>

                    @Html.EditorFor(model => model.CMND, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Nhập số CMND..." } })
                    @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })

                </div>

                <div class="form-group minHeight80">
                    <label>Địa chỉ liên hệ</label>
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Nhập địa chỉ..." } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>

                <div class="form-group minHeight80">
                    <label>Số điện thoại</label>
                    @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Nhập Số điện thoại..." } })
                    @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                </div>
                <div class="form-group minHeight80">
                    <label>Giới Tính</label>
                    @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Nhập Giới tính..." } })
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>


            </div>
        </div>
    </div>
}

QLTour/WebTour/Views/KhachHangs/Index.cshtml
@model IEnumerable<BusAndModel.Model.KhachHang>

@{
    ViewBag.Title = "Danh Sách Khách Hàng";
}

<div class="box">
    <div class="box-header text-center">
        <h3>Danh sách hành khách</h3>
        <div class="box-tools pull-right">
            <span class="btn btn-box-tool" onclick="location.href='/KhachHangs/Create'">
                <i class="fa fa-plus" style="font-size:16px"></i>
            </span>
        </div>
    </div>
    <div class="box-body">
        <table id="example2" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Họ và Tên</th>
                    <th>CMND</th>
                    <th>Địa Chỉ</th>
                    <th>Số điện thoại</th>
                    <th>Giới tính</th>
                    <th>Chức Năng</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.HoTen</td>
                        <td>@item.CMND</td>
                        <td>@item.DiaChi</td>
                        <td>@item.SDT</td>
                        <td>@item.GioiTinh</td>
                        <td class="text-center">
                            <button type="submit" class="btn btn-box-tool" onclick="location.href='/KhachHangs/Edit/'+@item.Id">
                                <i class="fa fa-edit" style="font-size:15px"></i>
                            </button>
                            <button type="submit" class="btn btn-box-tool" onclick="location.href='/KhachHangs/Delete/'+@item.Id">
                                <i class="fa fa-times" style="font-size:15px"></i>
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th>Id</th>
                    <th>Họ và Tên</th>
                    <th>CMND</th>
                    <th>Địa Chỉ</th>
                    <th>Số điện thoại</th>
                    <th>Giới tính</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>